[package]
name = "rsize"
version = "0.1.4"
authors = ["koopa1338 <sinner1991@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "3.1.14", features = ["derive"] }
image = "0.24.2"
rayon = "1.5.2"

[profile.release]
lto = "fat"
codegen-units = 1
strip = true
