[package]
name = "rsize"
version = "0.1.3"
authors = ["koopa1338 <sinner1991@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "3.1.3", features = ["derive"] }
image = "0.24.1"
rayon = "1.5.1"

[profile.release]
lto = "fat"
codegen-units = 1
