[package]
name = "rsize"
version = "0.1.5"
authors = ["koopa1338 <sinner1991@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
image = "0.24"
rayon = "1.7"

[profile.release]
lto = "fat"
codegen-units = 1
strip = true
