[package]
name = "rsize"
version = "0.1.1"
authors = ["koopa1338 <sinner1991@gmail.com>"]
edition = "2021"

[dependencies]
clap = "2.33.3"
image = "0.23.14"
rayon = "1.5.1"

[profile.release]
lto = "fat"
codegen-units = 1
